export const actionTypes = {
  SET_WEATHER: "SET_WEATHER",
  SET_DATES: "SET_DATES",
  SET_TEMPS: "SET_TEMPS",
  SET_LOCATION: "SET_LOCATION",
  PUSH_TO_DATES: "PUSH_TO_DATES",
  PUSH_TO_TEMPS: "PUSH_TO_TEMPS"
};
